# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'add_module_menu.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_window(object):
    def setupUi(self, window):
        window.setObjectName("window")
        window.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(window)
        self.centralwidget.setObjectName("centralwidget")
        self.back_button = QtWidgets.QPushButton(self.centralwidget)
        self.back_button.setGeometry(QtCore.QRect(0, 0, 150, 50))
        self.back_button.setObjectName("back_button")
        self.atachments_button = QtWidgets.QPushButton(self.centralwidget)
        self.atachments_button.setEnabled(False)
        self.atachments_button.setGeometry(QtCore.QRect(30, 130, 93, 28))
        self.atachments_button.setObjectName("atachments_button")
        self.save_button = QtWidgets.QPushButton(self.centralwidget)
        self.save_button.setEnabled(False)
        self.save_button.setGeometry(QtCore.QRect(30, 180, 150, 50))
        self.save_button.setObjectName("save_button")
        self.label_title = QtWidgets.QLabel(self.centralwidget)
        self.label_title.setGeometry(QtCore.QRect(30, 70, 120, 16))
        self.label_title.setObjectName("label_title")
        self.file_address = QtWidgets.QTextEdit(self.centralwidget)
        self.file_address.setGeometry(QtCore.QRect(30, 90, 250, 31))
        self.file_address.setObjectName("file_address")
        self.browse_file_button = QtWidgets.QPushButton(self.centralwidget)
        self.browse_file_button.setGeometry(QtCore.QRect(300, 90, 25, 25))
        self.browse_file_button.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("icons/add_doc.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.browse_file_button.setIcon(icon)
        self.browse_file_button.setObjectName("browse_file_button")
        window.setCentralWidget(self.centralwidget)

        self.retranslateUi(window)
        QtCore.QMetaObject.connectSlotsByName(window)

    def retranslateUi(self, window):
        _translate = QtCore.QCoreApplication.translate
        window.setWindowTitle(_translate("window", "Новый модуль"))
        self.back_button.setText(_translate("window", "Назад"))
        self.atachments_button.setText(_translate("window", "Вложения"))
        self.save_button.setText(_translate("window", "Сохранить модуль"))
        self.label_title.setText(_translate("window", "Поиск библиотеки:"))
