# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'boards_connect.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_mainWindow(object):
    def setupUi(self, mainWindow):
        mainWindow.setObjectName("mainWindow")
        mainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(mainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.button_back = QtWidgets.QPushButton(self.centralwidget)
        self.button_back.setGeometry(QtCore.QRect(30, 490, 160, 80))
        self.button_back.setObjectName("button_back")
        self.button_connect = QtWidgets.QPushButton(self.centralwidget)
        self.button_connect.setEnabled(False)
        self.button_connect.setGeometry(QtCore.QRect(30, 230, 321, 91))
        self.button_connect.setObjectName("button_connect")
        self.box_connection_params = QtWidgets.QGroupBox(self.centralwidget)
        self.box_connection_params.setGeometry(QtCore.QRect(30, 30, 330, 180))
        self.box_connection_params.setObjectName("box_connection_params")
        self.box_usb_ports = QtWidgets.QComboBox(self.box_connection_params)
        self.box_usb_ports.setGeometry(QtCore.QRect(30, 40, 73, 22))
        self.box_usb_ports.setObjectName("box_usb_ports")
        self.box_usb_ports.addItems(['COM1','COM2','COM3','COM4','COM5'])
        self.button_accept_params = QtWidgets.QPushButton(self.box_connection_params)
        self.button_accept_params.setGeometry(QtCore.QRect(30, 140, 93, 28))
        self.button_accept_params.setObjectName("button_accept_params")
        self.box_baudrate = QtWidgets.QComboBox(self.box_connection_params)
        self.box_baudrate.setGeometry(QtCore.QRect(30, 90, 73, 22))
        self.box_baudrate.setObjectName("box_baudrate")
        self.box_baudrate.addItems(['9600','19200','38400','57600','115200'])
        self.box_command_window = QtWidgets.QGroupBox(self.centralwidget)
        self.box_command_window.setEnabled(True)
        self.box_command_window.setGeometry(QtCore.QRect(420, 30, 330, 300))
        self.box_command_window.setObjectName("box_command_window")
        self.input_command = QtWidgets.QLineEdit(self.box_command_window)
        self.input_command.setGeometry(QtCore.QRect(0, 265, 330, 30))
        self.input_command.setObjectName("lineEdit")
        self.plainTextEdit = QtWidgets.QPlainTextEdit(self.box_command_window)
        self.plainTextEdit.setGeometry(QtCore.QRect(0, 20, 330, 240))
        self.plainTextEdit.setReadOnly(True)
        self.plainTextEdit.setObjectName("plainTextEdit")
        self.button_send_command = QtWidgets.QPushButton(self.box_command_window)
        self.button_send_command.setGeometry(QtCore.QRect(290, 265, 40, 30))
        self.button_send_command.setObjectName("button_send_command")
        mainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(mainWindow)
        QtCore.QMetaObject.connectSlotsByName(mainWindow)

    def retranslateUi(self, mainWindow):
        _translate = QtCore.QCoreApplication.translate
        mainWindow.setWindowTitle(_translate("mainWindow", "Boards"))
        self.button_back.setText(_translate("mainWindow", "Назад"))
        self.button_connect.setText(_translate("mainWindow", "Подключиться"))
        self.box_connection_params.setTitle(_translate("mainWindow", "Настройки подключения"))
        self.button_accept_params.setText(_translate("mainWindow", "Применить"))
        self.box_command_window.setTitle(_translate("mainWindow", "Окно управления"))
        self.button_send_command.setText(_translate("mainWindow", "Send"))
