# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main_menu_design.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_main_menu(object):
    def setupUi(self, main_menu):
        main_menu.setObjectName("main_menu")
        main_menu.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(main_menu)
        self.centralwidget.setObjectName("centralwidget")
        self.exit_button = QtWidgets.QPushButton(self.centralwidget)
        self.exit_button.setGeometry(QtCore.QRect(100, 475, 600, 100))
        self.exit_button.setObjectName("exit_button")
        self.settings_button = QtWidgets.QPushButton(self.centralwidget)
        self.settings_button.setGeometry(QtCore.QRect(100, 325, 600, 100))
        self.settings_button.setObjectName("settings_button")
        self.notes_button = QtWidgets.QPushButton(self.centralwidget)
        self.notes_button.setGeometry(QtCore.QRect(100, 175, 600, 100))
        self.notes_button.setObjectName("notes_button")
        self.boards_button = QtWidgets.QPushButton(self.centralwidget)
        self.boards_button.setGeometry(QtCore.QRect(100, 25, 600, 100))
        self.boards_button.setObjectName("boards_button")
        main_menu.setCentralWidget(self.centralwidget)

        self.retranslateUi(main_menu)
        QtCore.QMetaObject.connectSlotsByName(main_menu)

    def retranslateUi(self, main_menu):
        _translate = QtCore.QCoreApplication.translate
        main_menu.setWindowTitle(_translate("main_menu", "Главное Меню"))
        self.exit_button.setText(_translate("main_menu", "Выход"))
        self.settings_button.setText(_translate("main_menu", "Настройки"))
        self.notes_button.setText(_translate("main_menu", "Заметки"))
        self.boards_button.setText(_translate("main_menu", "Arduino"))
