# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'settings.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_window(object):
    def setupUi(self, window):
        window.setObjectName("window")
        window.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(window)
        self.centralwidget.setObjectName("centralwidget")
        self.back_button = QtWidgets.QPushButton(self.centralwidget)
        self.back_button.setGeometry(QtCore.QRect(0, 0, 150, 50))
        self.back_button.setObjectName("back_button")
        self.module_menu_button = QtWidgets.QPushButton(self.centralwidget)
        self.module_menu_button.setEnabled(True)
        self.module_menu_button.setGeometry(QtCore.QRect(60, 110, 150, 50))
        self.module_menu_button.setObjectName("module_menu_button")
        window.setCentralWidget(self.centralwidget)

        self.retranslateUi(window)
        QtCore.QMetaObject.connectSlotsByName(window)

    def retranslateUi(self, window):
        _translate = QtCore.QCoreApplication.translate
        window.setWindowTitle(_translate("window", "Настройки"))
        self.back_button.setText(_translate("window", "Назад"))
        self.module_menu_button.setText(_translate("window", "Управление модулями"))
